apiVersion: v1
kind: ReplicationController
metadata:
  name: web-#GROUP#
  labels:
    name: web-#GROUP#
spec:
  replicas: 1 #NUMBER#  
  template:
    metadata:
      labels:
        name: web-#GROUP#
    spec:
      containers:
        - name: web
          image: go-web-simple:1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8181
              name: http
          env:
          - name: GROUP
            value: "#GROUP#"
